name: vlc_clone
description: "A clean media player application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  file_picker: ^10.3.3
  path: ^1.8.3
  
  # Replace flutter_vlc_player with media_kit
  media_kit: ^1.2.0
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.11  # Windows-specific library
  provider: ^6.1.5+1
  hotkey_manager: ^0.2.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/